---
development:
  cloud_name: careforme
  api_key: '997521751119715'
  api_secret: CIGtwOx0nhj-okj6_q0NZerysZo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: careforme
  api_key: '997521751119715'
  api_secret: CIGtwOx0nhj-okj6_q0NZerysZo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: careforme
  api_key: '997521751119715'
  api_secret: CIGtwOx0nhj-okj6_q0NZerysZo
  enhance_image_tag: true
  static_image_support: false
