---
development:
  cloud_name: dlite9gd1
  api_key: '635751587857683'
  api_secret: nxVhiWcqD4w_mSOjCBgj-Igeh54
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dlite9gd1
  api_key: '635751587857683'
  api_secret: nxVhiWcqD4w_mSOjCBgj-Igeh54
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dlite9gd1
  api_key: '635751587857683'
  api_secret: nxVhiWcqD4w_mSOjCBgj-Igeh54
  enhance_image_tag: true
  static_image_support: false
